import { ReportData } from "../types";

const APP_ID = "cli_a9a2a01b94781cd4";
const APP_SECRET = "OT3MM3QOdaArCpfmP5wvlbgQSGd5nmbP";

// 使用 CORS 代理 (仅用于演示/开发环境，生产环境请使用后端转发)
// 这是一个公共演示代理，并不保证 100% 稳定。如果失败，说明需要部署真正的后端。
export const CORS_PROXY = "https://cors-anywhere.herokuapp.com/"; 

export const getTenantAccessToken = async (): Promise<string> => {
  try {
    const url = "https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal";
    
    // 尝试直接请求 (如果浏览器禁用了安全策略)
    try {
        const response = await fetch(url, {
            method: "POST",
            headers: { "Content-Type": "application/json; charset=utf-8" },
            body: JSON.stringify({ app_id: APP_ID, app_secret: APP_SECRET }),
        });
        if (response.ok) {
            const data = await response.json();
            return data.tenant_access_token;
        }
    } catch (e) {
        console.warn("Direct fetch failed (expected CORS), trying proxy...");
    }

    // 尝试使用 Proxy
    // 注意：用户需要先访问 https://cors-anywhere.herokuapp.com/demo 申请临时权限才能使用此公共代理
    const proxyResponse = await fetch(`${CORS_PROXY}${url}`, {
        method: "POST",
        headers: { "Content-Type": "application/json; charset=utf-8" },
        body: JSON.stringify({ app_id: APP_ID, app_secret: APP_SECRET }),
    });

    if (!proxyResponse.ok) {
        const errText = await proxyResponse.text();
        throw new Error(`Auth Failed: ${proxyResponse.status} ${proxyResponse.statusText} - ${errText}`);
    }

    const data = await proxyResponse.json();
    return data.tenant_access_token;

  } catch (error: any) {
    console.error("Error getting Feishu token:", error);
    throw new Error(`飞书鉴权失败 (CORS 限制)。请检查浏览器控制台。错误: ${error.message}`);
  }
};

interface ChatItem {
    chat_id: string;
    name: string;
}

export const getBotGroups = async (token: string): Promise<ChatItem[]> => {
    try {
        const url = `https://open.feishu.cn/open-apis/im/v1/chats?page_size=100`;
        
        // 同样尝试 Proxy
        const response = await fetch(`${CORS_PROXY}${url}`, {
            method: "GET",
            headers: {
                "Authorization": `Bearer ${token}`,
            }
        });

        if (!response.ok) {
            console.warn("Failed to fetch chat list via proxy.");
            return []; 
        }

        const data = await response.json();
        if (data.code !== 0) {
             console.error("Feishu API Error:", data);
             return [];
        }
        return data.data?.items || [];
    } catch (e) {
        console.error("Error fetching groups:", e);
        return [];
    }
}

const createFeishuCard = (data: ReportData) => {
  const elements = data.games.flatMap((game) => [
    {
      tag: "div",
      text: {
        tag: "lark_md",
        content: `**🎮 ${game.name}**\n${game.description}\n\n**🧩 核心玩法:** ${game.gameplayMechanics}\n**📊 适配评分:** ${game.rokCodFeasibilityScore}/10\n*💡 结合建议: ${game.rokCodAnalysis}*`
      }
    },
    {
      tag: "action",
      actions: [
        {
          tag: "button",
          text: { tag: "plain_text", content: "📺 观看 Gameplay" },
          url: game.youtubeQuery,
          type: "danger"
        },
        {
          tag: "button",
          text: { tag: "plain_text", content: "▶️ Google Play" },
          url: game.googlePlayLink,
          type: "primary"
        }
      ]
    },
    {
      tag: "hr"
    }
  ]);

  if (elements.length > 0) elements.pop();

  return {
    config: { wide_screen_mode: true },
    header: {
      template: "blue",
      title: { tag: "plain_text", content: `📅 每日新游监测报告: ${data.date}` }
    },
    elements: [
      {
        tag: "div",
        text: { tag: "lark_md", content: `**📝 市场总结:** ${data.summary}` }
      },
      { tag: "hr" },
      ...elements,
      {
        tag: "note",
        elements: [{ tag: "plain_text", content: "Generated by SLG Scout AI" }]
      }
    ]
  };
};

export const broadcastToFeishu = async (data: ReportData) => {
  try {
    const token = await getTenantAccessToken();
    const groups = await getBotGroups(token);

    if (groups.length === 0) {
        throw new Error("未找到机器人所在的群组。可能原因：1. 机器人未被拉入群组 2. CORS 阻止了列表获取。");
    }

    const cardContent = createFeishuCard(data);
    const results = [];

    for (const group of groups) {
        const url = `https://open.feishu.cn/open-apis/im/v1/messages?receive_id_type=chat_id`;
        const response = await fetch(`${CORS_PROXY}${url}`, {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${token}`,
                "Content-Type": "application/json; charset=utf-8",
            },
            body: JSON.stringify({
                receive_id: group.chat_id,
                msg_type: "interactive",
                content: JSON.stringify(cardContent),
            }),
        });
        
        results.push({
            id: group.chat_id,
            name: group.name,
            status: response.ok ? 'success' : 'failed'
        });
    }

    return results;
  } catch (error) {
    console.error("Feishu Broadcast Error:", error);
    throw error;
  }
};